#!/bin/bash

#docker build --pull -t docker.io/sumpfgottheit/aw-python .
docker build --pull -t registry.earlybird.at:5000/earlybird/aw-python .
docker push registry.earlybird.at:5000/earlybird/aw-python
